#include "sw.h"

#include <dirent.h>
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

const os_def *profile_os(const profile_t *p)
{
    const os_def *os = os_find(p->os);
    if (!os)
        die("profile '%s' uses unknown OS '%s' (fix it with: %s profile set %s os OS)",
            p->name, p->os, sw_prog, p->name);
    if (!os_available(os))
        die("profile '%s' (%s) cannot run on this computer", p->name, os->pretty);
    return os;
}

const char *profile_shell(const profile_t *p, const os_def *os)
{
    return p->shell[0] ? p->shell : os->shell;
}

const char *profile_platform(const profile_t *p, const os_def *os)
{
    if (!strcmp(p->arch, "amd64"))
        return "linux/amd64";
    if (!strcmp(p->arch, "arm64"))
        return "linux/arm64";
    return os->platform;
}

void image_name(const profile_t *p, char *out, size_t n)
{
    snprintf(out, n, "sw-%s", p->name);
}

/* ---- docker ---------------------------------------------------------- */

bool docker_running(void)
{
    char buf[128];
    char *argv[] = {"docker", "info", "--format", "{{.ServerVersion}}", NULL};
    return have_cmd("docker") && run_capture(argv, buf, sizeof buf) == 0 && buf[0];
}

void ensure_docker(void)
{
    if (!have_cmd("docker"))
        die("Linux profiles need Docker, and 'docker' is not in PATH.\n"
            "Install Docker Desktop: https://www.docker.com/products/docker-desktop/");
    if (docker_running())
        return;
#ifdef __APPLE__
    note("Docker is not running; starting Docker Desktop...");
    char *open_argv[] = {"open", "-g", "-a", "Docker", NULL};
    run_wait(open_argv, NULL, true);
    for (int i = 0; i < 120; i++) {
        sleep(1);
        if (docker_running())
            return;
    }
#endif
    die("the Docker daemon is not running; start Docker and try again");
}

static void sq_list(sb_t *b, const av_t *list)
{
    for (size_t i = 0; i < list->n; i++) {
        sb_add(b, " ");
        sb_add_sq(b, list->v[i]);
    }
}

/* Layers go base toolset, then your user, then extra tools, so changing the
 * tools only rebuilds the last layer and profiles on one OS share the rest. */
static void dockerfile(const profile_t *p, const os_def *os, sb_t *df)
{
    const char *user = host_user();
    const char *shell = profile_shell(p, os);
    unsigned uid = (unsigned)getuid(), gid = (unsigned)getgid();
    char home[320];
    snprintf(home, sizeof home, "/home/%s", user);

    sb_addf(df, "# Generated by sw for profile '%s'; rebuilt when the profile changes.\n", p->name);
    sb_addf(df, "FROM %s\n", os->image);
    sb_addf(df, "RUN %s\n", os->base_setup);

    sb_add(df, "RUN ");
    if (os->pkg == PKG_APK) {
        sb_addf(df, "g=$(awk -F: '$3==%u{print $1}' /etc/group); if [ -n \"$g\" ]; then "
                    "sed -i \"s/^$g:/", gid);
        sb_add(df, user);
        sb_addf(df, ":/\" /etc/group; else addgroup -g %u ", gid);
        sb_add_sq(df, user);
        sb_add(df, "; fi && adduser -D -H -u ");
        sb_addf(df, "%u -G ", uid);
        sb_add_sq(df, user);
        sb_add(df, " -h ");
        sb_add_sq(df, home);
        sb_add(df, " -s ");
        sb_add_sq(df, shell);
        sb_add(df, " ");
        sb_add_sq(df, user);
    } else {
        /* Name your primary group after you, as a normal account's is. */
        sb_addf(df, "{ g=$(getent group %u | cut -d: -f1); if [ -n \"$g\" ]; then "
                    "groupmod -n ", gid);
        sb_add_sq(df, user);
        sb_addf(df, " \"$g\"; else groupadd -g %u ", gid);
        sb_add_sq(df, user);
        sb_addf(df, "; fi; } && useradd -o -M -N -u %u -g %u -d ", uid, gid);
        sb_add_sq(df, home);
        sb_add(df, " -s ");
        sb_add_sq(df, shell);
        sb_add(df, " ");
        sb_add_sq(df, user);
    }
    sb_add(df, " && mkdir -p ");
    sb_add_sq(df, home);
    sb_addf(df, " && chown %u:%u ", uid, gid);
    sb_add_sq(df, home);
    sb_add(df, "\n");

    if (p->tools.n) {
        sb_add(df, "RUN ");
        switch (os->pkg) {
        case PKG_APT:
            sb_add(df, "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Retries=5 install -y");
            sq_list(df, &p->tools);
            sb_add(df, " && apt-get clean");
            break;
        case PKG_DNF:
            sb_add(df, "dnf -y install");
            sq_list(df, &p->tools);
            sb_add(df, " && dnf clean all");
            break;
        case PKG_PACMAN:
            sb_add(df, "pacman -Sy --noconfirm --needed");
            sq_list(df, &p->tools);
            break;
        case PKG_APK:
            sb_add(df, "apk add --no-cache");
            sq_list(df, &p->tools);
            break;
        case PKG_BREW:
            break;
        }
        sb_add(df, "\n");
    }
}

static void image_hash(const profile_t *p, const os_def *os, const sb_t *df, char *out, size_t n)
{
    const char *plat = profile_platform(p, os);
    unsigned long long h = fnv1a(sb_str(df), 0);
    h = fnv1a(plat ? plat : "native", h);
    snprintf(out, n, "%016llx", h);
}

static bool inspect_image(const char *img, const char *format, char *out, size_t n)
{
    char *argv[] = {"docker", "image", "inspect", "--format", (char *)format, (char *)img, NULL};
    return run_capture(argv, out, n) == 0;
}

img_state image_state(const profile_t *p)
{
    const os_def *os = os_find(p->os);
    if (!os || os->backend != BACKEND_CONTAINER || !docker_running())
        return IMG_UNKNOWN;
    sb_t df = {0};
    char hash[32], cur[128], img[128];
    dockerfile(p, os, &df);
    image_hash(p, os, &df, hash, sizeof hash);
    sb_free(&df);
    image_name(p, img, sizeof img);
    if (!inspect_image(img, "{{index .Config.Labels \"sw.hash\"}}", cur, sizeof cur))
        return IMG_MISSING;
    return strcmp(cur, hash) ? IMG_STALE : IMG_READY;
}

/* Build the profile's image unless an up-to-date one exists. 0 on success. */
int build_image(const profile_t *p, bool force, bool pull)
{
    const os_def *os = profile_os(p);
    sb_t df = {0};
    char hash[32], cur[128], oldid[128] = "", img[128];
    dockerfile(p, os, &df);
    image_hash(p, os, &df, hash, sizeof hash);
    image_name(p, img, sizeof img);

    bool exists = inspect_image(img, "{{index .Config.Labels \"sw.hash\"}}", cur, sizeof cur);
    if (exists && !force && !strcmp(cur, hash)) {
        sb_free(&df);
        return 0;
    }
    if (exists)
        inspect_image(img, "{{.Id}}", oldid, sizeof oldid);

    char dir[SW_PATH], path[SW_PATH];
    profile_dir(p->name, dir, sizeof dir);
    mkdir_p(dir);
    snprintf(path, sizeof path, "%s/Dockerfile", dir);
    write_file(path, sb_str(&df));
    sb_free(&df);

    if (exists)
        note("rebuilding image %s for profile '%s'...", img, p->name);
    else
        note("building image %s for profile '%s' from %s "
             "(the first build downloads the base toolset and takes a few minutes)...",
             img, p->name, os->image);

    const char *plat = profile_platform(p, os);
    av_t a = {0};
    av_push(&a, "docker");
    av_push(&a, "build");
    if (pull)
        av_push(&a, "--pull");
    if (plat)
        av_pushf(&a, "--platform=%s", plat);
    av_pushf(&a, "--tag=%s", img);
    av_pushf(&a, "--label=sw.hash=%s", hash);
    av_pushf(&a, "--label=sw.profile=%s", p->name);
    av_push(&a, "-");
    int rc = run_wait(a.v, path, false);
    av_free(&a);

    char newid[128];
    if (rc == 0 && oldid[0] && inspect_image(img, "{{.Id}}", newid, sizeof newid) &&
        strcmp(oldid, newid)) {
        char *rm[] = {"docker", "image", "rm", oldid, NULL};
        run_wait(rm, NULL, true);
    }
    return rc;
}

/* ---- Homebrew (macOS profiles) --------------------------------------- */

const char *brew_prefix(void)
{
    const char *e = getenv("HOMEBREW_PREFIX");
    if (e && *e)
        return e;
    return is_dir("/opt/homebrew") ? "/opt/homebrew" : "/usr/local";
}

static const char *formula_base(const char *name)
{
    const char *s = strrchr(name, '/');
    return s ? s + 1 : name;
}

bool brew_formula_installed(const char *name)
{
    char path[SW_PATH];
    snprintf(path, sizeof path, "%s/opt/%s", brew_prefix(), formula_base(name));
    return is_dir(path);
}

/* Rebuild the profile's bin/ as links to exactly the chosen formulae. */
void native_link_tools(const profile_t *p)
{
    char dir[SW_PATH], bin[SW_PATH];
    profile_dir(p->name, dir, sizeof dir);
    snprintf(bin, sizeof bin, "%s/bin", dir);
    rm_rf(bin);
    if (mkdir_p(bin))
        die("cannot create %s: %s", bin, strerror(errno));

    for (size_t i = 0; i < p->tools.n; i++) {
        const char *t = p->tools.v[i];
        if (t[0] == '@')
            continue;
        int linked = 0;
        const char *subs[] = {"bin", "sbin"};
        for (int s = 0; s < 2; s++) {
            char src[SW_PATH];
            snprintf(src, sizeof src, "%s/opt/%s/%s", brew_prefix(), formula_base(t), subs[s]);
            DIR *d = opendir(src);
            if (!d)
                continue;
            struct dirent *e;
            while ((e = readdir(d))) {
                if (e->d_name[0] == '.')
                    continue;
                char to[SW_PATH], link[SW_PATH];
                snprintf(to, sizeof to, "%s/%s", src, e->d_name);
                snprintf(link, sizeof link, "%s/%s", bin, e->d_name);
                if (symlink(to, link) == 0)
                    linked++;
            }
            closedir(d);
        }
        if (!linked)
            sw_warn("Homebrew formula '%s' has no programs to share", t);
    }
}

static bool shares_all_brew(const profile_t *p)
{
    return av_find(&p->tools, "@all") >= 0;
}

/* ---- shell setup ----------------------------------------------------- */

typedef enum { SH_BASH, SH_ZSH, SH_POSIX, SH_OTHER } sh_kind;

static sh_kind shell_kind(const char *shell)
{
    const char *b = strrchr(shell, '/');
    b = b ? b + 1 : shell;
    if (!strcmp(b, "bash"))
        return SH_BASH;
    if (!strcmp(b, "zsh"))
        return SH_ZSH;
    if (!strcmp(b, "sh") || !strcmp(b, "ash") || !strcmp(b, "dash") ||
        !strcmp(b, "ksh") || !strcmp(b, "mksh") || !strcmp(b, "busybox"))
        return SH_POSIX;
    return SH_OTHER;
}

static void add_custom(sb_t *b, const char *base)
{
    char custom[SW_PATH];
    snprintf(custom, sizeof custom, "%s/custom.sh", base);
    sb_add(b, "[ -r ");
    sb_add_sq(b, custom);
    sb_add(b, " ] && . ");
    sb_add_sq(b, custom);
    sb_add(b, "\n");
}

static void add_sw_function(sb_t *b)
{
    sb_add(b, "sw() {\n"
              "  case \"${1-}\" in\n"
              "    exit) exit \"${2:-0}\" ;;\n"
              "    *) echo \"sw: you are inside profile '$SW_PROFILE' ($SW_OS). "
              "Type 'exit' or 'sw exit' to go back.\" >&2; return 1 ;;\n"
              "  esac\n"
              "}\n"
              "switch() { sw \"$@\"; }\n");
}

/* Write rc (bash and POSIX shells), .zshenv and .zshrc into the profile
 * directory. base is that directory as the shell sees it; native_path is
 * the PATH to force, for native profiles. */
static void write_shell_files(const profile_t *p, const os_def *os, const char *dir,
                              const char *base, const char *native_path)
{
    char path[SW_PATH], hist[SW_PATH];
    snprintf(hist, sizeof hist, "%s/history", base);

    sb_t head = {0};
    sb_addf(&head, "# Generated by sw for profile '%s' (%s).\n"
                   "# Rewritten on every switch: put your own settings in custom.sh.\n",
            p->name, os->pretty);

    sb_t rc = {0};
    sb_add(&rc, sb_str(&head));
    sb_add(&rc, "[ -r /etc/profile ] && . /etc/profile\n"
                "if [ -n \"${BASH_VERSION-}\" ] && [ -r /etc/skel/.bashrc ]; then "
                ". /etc/skel/.bashrc; fi\n");
    if (native_path) {
        sb_add(&rc, "PATH=");
        sb_add_sq(&rc, native_path);
        sb_add(&rc, "; export PATH\n");
    }
    sb_add(&rc, "HISTFILE=");
    sb_add_sq(&rc, hist);
    sb_add(&rc, "\n");
    add_custom(&rc, base);
    add_sw_function(&rc);
    snprintf(path, sizeof path, "%s/rc", dir);
    write_file(path, sb_str(&rc));

    sb_t zenv = {0};
    sb_add(&zenv, sb_str(&head));
    if (native_path) {
        sb_add(&zenv, "export PATH=");
        sb_add_sq(&zenv, native_path);
        sb_add(&zenv, "\n");
    }
    add_sw_function(&zenv); /* .zshenv is read by every zsh, interactive or not */
    snprintf(path, sizeof path, "%s/.zshenv", dir);
    write_file(path, sb_str(&zenv));

    sb_t zrc = {0};
    sb_add(&zrc, sb_str(&head));
    add_custom(&zrc, base);
    snprintf(path, sizeof path, "%s/.zshrc", dir);
    write_file(path, sb_str(&zrc));

    snprintf(path, sizeof path, "%s/custom.sh", dir);
    if (!path_exists(path)) {
        sb_t c = {0};
        sb_addf(&c, "# Your own settings for sw profile '%s': aliases, PS1, exports...\n"
                    "# Sourced by the profile's shell on every switch; sw never overwrites it.\n",
                p->name);
        write_file(path, sb_str(&c));
        sb_free(&c);
    }
    sb_free(&head);
    sb_free(&rc);
    sb_free(&zenv);
    sb_free(&zrc);
}

static void push_shell_env(av_t *env, bool docker, const char *shell, const char *base)
{
    const char *flag = docker ? "--env=" : "";
    switch (shell_kind(shell)) {
    case SH_ZSH:
        av_pushf(env, "%sZDOTDIR=%s", flag, base);
        break;
    case SH_POSIX:
        av_pushf(env, "%sENV=%s/rc", flag, base);
        break;
    default:
        break;
    }
}

static void push_shell_args(av_t *a, const char *shell, const char *base, const char *command)
{
    sh_kind k = shell_kind(shell);
    char rc[SW_PATH];
    snprintf(rc, sizeof rc, "%s/rc", base);
    av_push(a, shell);
    if (command) {
        av_push(a, "-c");
        if (k == SH_BASH || k == SH_POSIX) {
            sb_t s = {0};
            sb_add(&s, ". ");
            sb_add_sq(&s, rc);
            sb_add(&s, " >/dev/null 2>&1\n");
            sb_add(&s, command);
            av_push(a, sb_str(&s));
            sb_free(&s);
        } else {
            av_push(a, command);
        }
    } else {
        if (k == SH_BASH) {
            av_push(a, "--rcfile");
            av_push(a, rc);
        }
        av_push(a, "-i");
    }
}

static const char *host_tz(void)
{
    static char buf[256];
    const char *tz = getenv("TZ");
    if (tz && *tz)
        return tz;
    char link[SW_PATH];
    ssize_t n = readlink("/etc/localtime", link, sizeof link - 1);
    if (n <= 0)
        return NULL;
    link[n] = '\0';
    const char *z = strstr(link, "zoneinfo/");
    if (!z)
        return NULL;
    snprintf(buf, sizeof buf, "%s", z + 9);
    return buf;
}

/* ---- launching ------------------------------------------------------- */

static void launch_container(const profile_t *p, const os_def *os, const char *dir,
                             const char *lim, const char *cwd, const char *command)
{
    ensure_docker();
    if (build_image(p, false, false) != 0)
        die("could not build the image for profile '%s' (check its tools with: %s inspect %s tool)",
            p->name, sw_prog, p->name);
    write_shell_files(p, os, dir, SW_GUEST_DIR, NULL);

    const char *user = host_user();
    const char *shell = profile_shell(p, os);
    const char *plat = profile_platform(p, os);
    char img[128], home[SW_PATH], work[SW_PATH];
    image_name(p, img, sizeof img);

    av_t a = {0};
    av_push(&a, "docker");
    av_push(&a, "run");
    av_push(&a, "--rm");
    av_push(&a, "--interactive");
    if (is_tty())
        av_push(&a, "--tty");
    av_pushf(&a, "--name=sw-%s-%d", p->name, (int)getpid());
    av_pushf(&a, "--label=sw.session=%s", p->name);
    av_pushf(&a, "--hostname=%s", p->hostname[0] ? p->hostname : os->hostname);
    if (plat)
        av_pushf(&a, "--platform=%s", plat);
    av_pushf(&a, "--user=%u:%u", (unsigned)getuid(), (unsigned)getgid());

    if (lim[0]) {
        /* Limited: the directory is the whole world, mounted as a Linux home. */
        snprintf(home, sizeof home, "/home/%s", user);
        av_pushf(&a, "--volume=%s:%s", lim, home);
        if (path_under(cwd, lim))
            snprintf(work, sizeof work, "%s%s", home, cwd + strlen(lim));
        else
            snprintf(work, sizeof work, "%s", home);
    } else {
        /* Your file system, at the same paths as on the host. */
        bool home_shared = false, cwd_shared = false;
        snprintf(home, sizeof home, "%s", host_home());
        for (size_t i = 0; i < p->mounts.n; i++) {
            const char *m = p->mounts.v[i];
            if (!is_dir(m)) {
                sw_warn("shared directory %s does not exist; skipped", m);
                continue;
            }
            av_pushf(&a, "--volume=%s:%s", m, m);
            home_shared |= path_under(home, m);
            cwd_shared |= path_under(cwd, m);
        }
        if (!home_shared) {
            sw_warn("your home %s is not shared with profile '%s'", home, p->name);
            snprintf(home, sizeof home, "/home/%s", user);
        }
        snprintf(work, sizeof work, "%s", cwd_shared ? cwd : home);
    }
    av_pushf(&a, "--volume=%s:%s", dir, SW_GUEST_DIR);
    av_pushf(&a, "--workdir=%s", work);

    const char *term = getenv("TERM");
    const char *tz = host_tz();
    const char *colorterm = getenv("COLORTERM");
    av_pushf(&a, "--env=HOME=%s", home);
    av_pushf(&a, "--env=USER=%s", user);
    av_pushf(&a, "--env=LOGNAME=%s", user);
    av_pushf(&a, "--env=SHELL=%s", shell);
    av_pushf(&a, "--env=TERM=%s", term && *term ? term : "xterm-256color");
    av_push(&a, "--env=LANG=C.UTF-8");
    if (tz)
        av_pushf(&a, "--env=TZ=%s", tz);
    if (colorterm)
        av_pushf(&a, "--env=COLORTERM=%s", colorterm);
    av_pushf(&a, "--env=SW_PROFILE=%s", p->name);
    av_pushf(&a, "--env=SW_OS=%s", os->id);
    push_shell_env(&a, true, shell, SW_GUEST_DIR);

    av_push(&a, img);
    push_shell_args(&a, shell, SW_GUEST_DIR, command);

    fflush(NULL);
    execvp("docker", a.v);
    die("cannot run docker: %s", strerror(errno));
}

static void launch_native(const profile_t *p, const os_def *os, const char *dir,
                          const char *lim, const char *cwd, const char *command)
{
    const char *shell = profile_shell(p, os);
    native_link_tools(p);

    sb_t path = {0};
    sb_addf(&path, "%s/bin", dir);
    if (shares_all_brew(p))
        sb_addf(&path, ":%s/bin:%s/sbin", brew_prefix(), brew_prefix());
    sb_add(&path, ":/usr/bin:/bin:/usr/sbin:/sbin");
    write_shell_files(p, os, dir, dir, sb_str(&path));

    const char *home = lim[0] ? lim : host_home();
    const char *work = lim[0] && !path_under(cwd, lim) ? lim : cwd;
    if (chdir(work))
        sw_warn("cannot enter %s: %s", work, strerror(errno));

    const char *user = host_user();
    const char *term = getenv("TERM");
    av_t env = {0};
    av_pushf(&env, "HOME=%s", home);
    av_pushf(&env, "USER=%s", user);
    av_pushf(&env, "LOGNAME=%s", user);
    av_pushf(&env, "SHELL=%s", shell);
    av_pushf(&env, "PATH=%s", sb_str(&path));
    av_pushf(&env, "TERM=%s", term && *term ? term : "xterm-256color");
    av_pushf(&env, "SW_PROFILE=%s", p->name);
    av_pushf(&env, "SW_OS=%s", os->id);
    const char *keep[] = {"LANG", "TMPDIR", "COLORTERM", "TERM_PROGRAM",
                          "TERM_PROGRAM_VERSION", "SSH_AUTH_SOCK", "TZ", NULL};
    for (int i = 0; keep[i]; i++) {
        const char *v = getenv(keep[i]);
        if (v)
            av_pushf(&env, "%s=%s", keep[i], v);
    }
    push_shell_env(&env, false, shell, dir);

    av_t a = {0};
    push_shell_args(&a, shell, dir, command);
    sb_free(&path);

    fflush(NULL);
    execve(shell, a.v, env.v);
    die("cannot run %s: %s", shell, strerror(errno));
}

void launch(const profile_t *p, const char *limit, const char *command)
{
    const char *active = getenv("SW_PROFILE");
    if (active && *active)
        die("already inside profile '%s'; type 'exit' first", active);

    const os_def *os = profile_os(p);
    char dir[SW_PATH], lim[SW_PATH] = "", cwd[SW_PATH];
    profile_dir(p->name, dir, sizeof dir);
    if (mkdir_p(dir))
        die("cannot create %s: %s", dir, strerror(errno));

    if (limit) {
        snprintf(lim, sizeof lim, "%s", limit);
    } else if (p->home[0] && expand_path(p->home, lim, sizeof lim)) {
        die("cannot use home '%s' of profile '%s'", p->home, p->name);
    }
    if (lim[0]) {
        if (!strcmp(lim, "/"))
            die("cannot limit a profile to /");
        if (!path_exists(lim)) {
            if (mkdir_p(lim))
                die("cannot create %s: %s", lim, strerror(errno));
            note("created %s", lim);
            char real[SW_PATH];
            if (realpath(lim, real))
                snprintf(lim, sizeof lim, "%s", real);
        } else if (!is_dir(lim)) {
            die("%s is not a directory", lim);
        }
    }
    if (!getcwd(cwd, sizeof cwd))
        snprintf(cwd, sizeof cwd, "%s", host_home());

    if (os->backend == BACKEND_NATIVE)
        launch_native(p, os, dir, lim, cwd, command);
    else
        launch_container(p, os, dir, lim, cwd, command);
    exit(1); /* not reached */
}
